"use client";
import { useState } from "react";
import Link from "next/link";
import { formatPrice } from "@/lib/format";

type Order = { id: string; status: string; totalCents: number; addressLine: string; placedAt: Date; items: Array<{ productName: string; variantName: string; quantity: number; unitPriceCents: number }> };
const tabs = [{ key: "ALL", label: "All" }, { key: "TO_PAY", label: "To pay" }, { key: "TO_SHIP", label: "To ship" }, { key: "TO_RECEIVE", label: "To receive" }, { key: "COMPLETED", label: "Completed" }, { key: "CANCELLED", label: "Cancelled" }];
const labels: Record<string, string> = { TO_PAY: "To pay", TO_SHIP: "To ship", TO_RECEIVE: "To receive", COMPLETED: "Completed", CANCELLED: "Cancelled" };
export function OrdersView({ orders, initialTab, placed }: { orders: Order[]; initialTab?: string; placed?: string }) {
  const [tab, setTab] = useState(initialTab ?? "ALL"); const [list, setList] = useState(orders); const [message, setMessage] = useState(placed ? "Order placed successfully." : "");
  const filtered = tab === "ALL" ? list : list.filter((order) => order.status === tab);
  async function cancel(id: string) { const response = await fetch(`/api/orders/${id}`, { method: "POST" }); const body = await response.json(); if (!response.ok) return setMessage(body.error); setList((current) => current.map((order) => order.id === id ? { ...order, status: "CANCELLED" } : order)); setMessage("Order cancelled."); }
  return <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8"><div className="flex items-end justify-between"><div><p className="text-sm text-muted-foreground">My account</p><h1 className="text-2xl font-bold">My orders</h1></div><Link href="/products" className="text-sm text-primary hover:underline">Continue shopping</Link></div>{message && <p className="mt-4 rounded border border-primary/30 bg-primary/5 p-3 text-sm text-primary">{message}</p>}<div className="mt-6 flex gap-1 overflow-auto border-b border-border">{tabs.map((item) => <button type="button" key={item.key} onClick={() => setTab(item.key)} className={`whitespace-nowrap px-3 py-3 text-sm ${tab === item.key ? "border-b-2 border-primary font-semibold text-primary" : "text-muted-foreground"}`}>{item.label}</button>)}</div><div className="mt-5 space-y-4">{filtered.map((order) => <article key={order.id} className="rounded border border-border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-border pb-3"><span className="text-sm text-muted-foreground">Order #{order.id.slice(-8).toUpperCase()}</span><span className="font-medium text-primary">{labels[order.status]}</span></div><div className="divide-y divide-border">{order.items.map((item, index) => <div key={`${order.id}-${index}`} className="flex justify-between py-3 text-sm"><span>{item.productName} · {item.variantName} × {item.quantity}</span><span>{formatPrice(item.unitPriceCents * item.quantity)}</span></div>)}</div><p className="text-sm text-muted-foreground">{order.addressLine}</p><div className="mt-3 flex items-center justify-between border-t border-border pt-3"><strong>Total {formatPrice(order.totalCents)}</strong>{["TO_PAY", "TO_SHIP"].includes(order.status) && <button type="button" onClick={() => void cancel(order.id)} className="rounded border border-destructive px-3 py-1.5 text-sm text-destructive">Cancel order</button>}</div></article>)}{!filtered.length && <div className="rounded border border-border bg-card p-10 text-center text-muted-foreground">No orders in this tab.</div>}</div></div>;
}
