"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { shippingRates } from "@/lib/commerce";
import { formatPrice } from "@/lib/format";

type Address = { id: string; label: string; recipientName: string; phone: string; line1: string; line2: string | null; city: string; province: string; postalCode: string };
export function CheckoutForm({ addresses }: { addresses: Address[] }) {
  const router = useRouter(); const [addressId, setAddressId] = useState(addresses[0]?.id ?? ""); const [newAddress, setNewAddress] = useState(false); const [shippingOption, setShippingOption] = useState<"STANDARD" | "EXPRESS">("STANDARD"); const [paymentMethod, setPaymentMethod] = useState<"COD" | "MOCK">("COD"); const [error, setError] = useState("");
  const [fields, setFields] = useState({ label: "Home", recipientName: "", phone: "", line1: "", line2: "", city: "", province: "", postalCode: "" });
  function update(name: string, value: string) { setFields((current) => ({ ...current, [name]: value })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); const response = await fetch("/api/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ addressId: newAddress ? undefined : addressId, address: newAddress ? fields : undefined, shippingOption, paymentMethod }) }); const body = await response.json(); if (!response.ok) return setError(body.error); router.push(`/orders?placed=${body.orderId}`); }
  return <form onSubmit={submit} className="mx-auto max-w-5xl space-y-6 px-4 py-8 sm:px-6 lg:px-8"><h1 className="text-2xl font-bold">Checkout</h1>{error && <p className="rounded border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<section className="rounded border border-border bg-card p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Delivery address</h2><button type="button" className="text-sm text-primary" onClick={() => setNewAddress(!newAddress)}>{newAddress ? "Use saved address" : "Add new address"}</button></div>{!newAddress && addresses.length ? <select value={addressId} onChange={(event) => setAddressId(event.target.value)} className="mt-4 w-full rounded border border-input bg-background p-3">{addresses.map((address) => <option key={address.id} value={address.id}>{address.label} — {address.recipientName}, {address.line1}, {address.city}</option>)}</select> : <div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(fields).map(([name, value]) => <input key={name} required={name !== "line2"} value={value} onChange={(event) => update(name, event.target.value)} placeholder={name.replace(/([A-Z])/g, " $1")} className="rounded border border-input bg-background p-3" />)}</div>}</section><section className="rounded border border-border bg-card p-5"><h2 className="font-semibold">Shipping method</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{(["STANDARD", "EXPRESS"] as const).map((option) => <label key={option} className={`flex cursor-pointer justify-between rounded border p-3 ${shippingOption === option ? "border-primary" : "border-border"}`}><span><input type="radio" name="shipping" checked={shippingOption === option} onChange={() => setShippingOption(option)} /> <span className="ml-2">{option === "STANDARD" ? "Standard delivery" : "Express delivery"}</span></span><span>{shippingRates[option] ? formatPrice(shippingRates[option]) : "Free"}</span></label>)}</div></section><section className="rounded border border-border bg-card p-5"><h2 className="font-semibold">Payment</h2><div className="mt-3 space-y-3"><label className="block"><input type="radio" checked={paymentMethod === "COD"} onChange={() => setPaymentMethod("COD")} /> <span className="ml-2">Cash on delivery</span></label><label className="block"><input type="radio" checked={paymentMethod === "MOCK"} onChange={() => setPaymentMethod("MOCK")} /> <span className="ml-2">Demo online payment (no charge)</span></label></div></section><button className="w-full rounded bg-primary px-5 py-3 font-semibold text-primary-foreground hover:bg-primary/90">Place order</button></form>;
}
