"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { shippingRates } from "@/lib/commerce";
import { formatPrice } from "@/lib/format";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Address = { id: string; label: string; recipientName: string; phone: string; line1: string; line2: string | null; city: string; province: string; postalCode: string };
export function CheckoutForm({ addresses }: { addresses: Address[] }) {
  const router = useRouter(); const [addressId, setAddressId] = useState(addresses[0]?.id ?? ""); const [newAddress, setNewAddress] = useState(false); const [shippingOption, setShippingOption] = useState<"STANDARD" | "EXPRESS">("STANDARD"); const [paymentMethod, setPaymentMethod] = useState<"COD" | "MOCK">("COD"); const [error, setError] = useState("");
  const [fields, setFields] = useState({ label: "Home", recipientName: "", phone: "", line1: "", line2: "", city: "", province: "", postalCode: "" });
  function update(name: string, value: string) { setFields((current) => ({ ...current, [name]: value })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); const response = await fetch("/api/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ addressId: newAddress ? undefined : addressId, address: newAddress ? fields : undefined, shippingOption, paymentMethod }) }); const body = await response.json(); if (!response.ok) return setError(body.error); router.push(`/orders?placed=${body.orderId}`); }
  return <form onSubmit={submit} className="mx-auto max-w-5xl space-y-6 px-4 py-8 sm:px-6 lg:px-8"><h1 className="text-2xl font-bold">Checkout</h1>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}<Card><CardHeader className="flex-row items-center justify-between"><CardTitle className="text-base">Delivery address</CardTitle><Button type="button" variant="link" size="sm" onClick={() => setNewAddress(!newAddress)}>{newAddress ? "Use saved address" : "Add new address"}</Button></CardHeader><CardContent>{!newAddress && addresses.length ? <Select value={addressId} onValueChange={(value) => setAddressId(value ?? "")}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{addresses.map((address) => <SelectItem key={address.id} value={address.id}>{address.label} — {address.recipientName}, {address.line1}, {address.city}</SelectItem>)}</SelectContent></Select> : <div className="grid gap-3 sm:grid-cols-2">{Object.entries(fields).map(([name, value]) => <div key={name} className="space-y-1"><Label htmlFor={name}>{name.replace(/([A-Z])/g, " $1")}</Label><Input id={name} required={name !== "line2"} value={value} onChange={(event) => update(name, event.target.value)} /></div>)}</div>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Shipping method</CardTitle></CardHeader><CardContent><RadioGroup value={shippingOption} onValueChange={(value) => setShippingOption(value as "STANDARD" | "EXPRESS")} className="grid gap-3 sm:grid-cols-2">{(["STANDARD", "EXPRESS"] as const).map((option) => <Label key={option} htmlFor={option} className={`flex cursor-pointer justify-between rounded border p-3 ${shippingOption === option ? "border-primary" : "border-border"}`}><span className="flex items-center gap-2"><RadioGroupItem value={option} id={option} />{option === "STANDARD" ? "Standard delivery" : "Express delivery"}</span><span>{shippingRates[option] ? formatPrice(shippingRates[option]) : "Free"}</span></Label>)}</RadioGroup></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Payment</CardTitle></CardHeader><CardContent><RadioGroup value={paymentMethod} onValueChange={(value) => setPaymentMethod(value as "COD" | "MOCK")} className="space-y-3"><Label htmlFor="cod" className="flex items-center gap-2"><RadioGroupItem value="COD" id="cod" />Cash on delivery</Label><Label htmlFor="mock" className="flex items-center gap-2"><RadioGroupItem value="MOCK" id="mock" />Demo online payment (no charge)</Label></RadioGroup></CardContent></Card><Button className="w-full py-3 font-semibold">Place order</Button></form>;
}
